[env:stm32_example_madgwick]
platform = ststm32
board = disco_l475vg_iot01a
framework = arduino
monitor_speed = 115200

lib_extra_dirs =
    ../../lib
    ../../external
    ../../external/fusion

build_unflags =
    -std=gnu++11
    -std=gnu++14
    -std=gnu++17
    -std=c++11
    -std=c++14
    -std=c++17

build_flags =
    -std=gnu++20
    -Wall
	-Wextra
	-Werror
	; For MPU6050.
	; -DTINY_MPU6050_WHOAMI_VALUE=0x68
    ; For MPU6500.
    -DTINY_MPU6050_WHOAMI_VALUE=0x70
	-DTARGET_PLATFORM=ARDUINO
	-DTARGET_PLATFORM_ARDUINO

	; Explicitly tell the compiler where to find the deeply nested headers
    -I../../external/fusion/madgwick/include
    -I../../external/tl/include
    -I../../external/fmt/include
