[env:model_example]
platform = nordicnrf52
board = nano33ble
framework = arduino
monitor_speed = 115200

; Libraries
lib_deps =
    https://github.com/tensorflow/tflite-micro-arduino-examples.git
    arduino-libraries/Arduino_LSM9DS1@^1.1.0
    arduino-libraries/Arduino_BMI270_BMM150@^1.0.0

lib_extra_dirs =
    ../../lib
    ../../external
    ../../external/fusion

lib_ignore =
    eigen ; Otherwise it tries to compile files in their test/ and bench/
    bmi270-pid/bmi270_DSD_examples ; Exclude BMI270 example files
    Arduino_TensorFlowLite/src/peripherals ; Exclude TF peripheral files with chrono conflicts

; Remove old C++ standard flags
build_unflags =
    -std=gnu++11
    -std=gnu++14
    -std=c++11
    -std=c++14

; Build settings
build_flags =
    -std=gnu++17
    ; Optimize for size
    -Os
    ; Prioritize local include directory to use our Arduino.h wrapper
    -I$PROJECT_INCLUDE_DIR
    ; TensorFlow Lite options
    -DTF_LITE_STATIC_MEMORY
    -DTF_LITE_DISABLE_X86_NEON
    ; For MPU6500.
    -DTINY_MPU6050_WHOAMI_VALUE=0x70
    -DTARGET_PLATFORM=ARDUINO
    -DTARGET_PLATFORM_ARDUINO
    -DFUSION_USE_NORMAL_SQRT
	; https://github.com/arduino/ArduinoCore-mbed/issues/1024
	-DMBED_CONF_NORDIC_NRF_LF_CLOCK_SRC=NRF_LF_SRC_XTAL

    ; Explicitly tell the compiler where to find the deeply nested headers
    -I../../external/fusion/madgwick/include
    -I../../external/fusion/madgwick/
    -I../../external/tl/include
    -I../../external/fmt/include
    -I../../external/eigen/

extra_scripts = pre:./platformio/ignore_examples.py
