// ---------------------------------------------------------------- //
// This file is autogenerated by pioasm version 2.2.0; do not edit! //
// ---------------------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ---- //
// ec11 //
// ---- //

#define ec11_wrap_target 0
#define ec11_wrap 5
#define ec11_pio_version 0

static const uint16_t ec11_program_instructions[] = {
            //     .wrap_target
    0x2fa0, //  0: wait   1 pin, 0               [15]
    0x2f20, //  1: wait   0 pin, 0               [15]
    0xa02b, //  2: mov    x, ~null
    0x00c5, //  3: jmp    pin, 5
    0xa023, //  4: mov    x, null
    0x4021, //  5: in     x, 1
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program ec11_program = {
    .instructions = ec11_program_instructions,
    .length = 6,
    .origin = -1,
    .pio_version = ec11_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config ec11_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + ec11_wrap_target, offset + ec11_wrap);
    return c;
}
#endif

