/* DO NOT EDIT: This file is automatically generated by Cabal */

/* package clash-assignments-0.1 */
#ifndef VERSION_clash_assignments
#define VERSION_clash_assignments "0.1"
#endif /* VERSION_clash_assignments */
#ifndef MIN_VERSION_clash_assignments
#define MIN_VERSION_clash_assignments(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 0)
#endif /* MIN_VERSION_clash_assignments */
/* package Cabal-3.10.3.0 */
#ifndef VERSION_Cabal
#define VERSION_Cabal "3.10.3.0"
#endif /* VERSION_Cabal */
#ifndef MIN_VERSION_Cabal
#define MIN_VERSION_Cabal(major1,major2,minor) (\
  (major1) <  3 || \
  (major1) == 3 && (major2) <  10 || \
  (major1) == 3 && (major2) == 10 && (minor) <= 3)
#endif /* MIN_VERSION_Cabal */
/* package base-4.19.2.0 */
#ifndef VERSION_base
#define VERSION_base "4.19.2.0"
#endif /* VERSION_base */
#ifndef MIN_VERSION_base
#define MIN_VERSION_base(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  19 || \
  (major1) == 4 && (major2) == 19 && (minor) <= 2)
#endif /* MIN_VERSION_base */
/* package bytestring-0.12.1.0 */
#ifndef VERSION_bytestring
#define VERSION_bytestring "0.12.1.0"
#endif /* VERSION_bytestring */
#ifndef MIN_VERSION_bytestring
#define MIN_VERSION_bytestring(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  12 || \
  (major1) == 0 && (major2) == 12 && (minor) <= 1)
#endif /* MIN_VERSION_bytestring */
/* package clash-prelude-1.8.4 */
#ifndef VERSION_clash_prelude
#define VERSION_clash_prelude "1.8.4"
#endif /* VERSION_clash_prelude */
#ifndef MIN_VERSION_clash_prelude
#define MIN_VERSION_clash_prelude(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  8 || \
  (major1) == 1 && (major2) == 8 && (minor) <= 4)
#endif /* MIN_VERSION_clash_prelude */
/* package directory-1.3.8.5 */
#ifndef VERSION_directory
#define VERSION_directory "1.3.8.5"
#endif /* VERSION_directory */
#ifndef MIN_VERSION_directory
#define MIN_VERSION_directory(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  3 || \
  (major1) == 1 && (major2) == 3 && (minor) <= 8)
#endif /* MIN_VERSION_directory */
/* package ghc-typelits-extra-0.4.8 */
#ifndef VERSION_ghc_typelits_extra
#define VERSION_ghc_typelits_extra "0.4.8"
#endif /* VERSION_ghc_typelits_extra */
#ifndef MIN_VERSION_ghc_typelits_extra
#define MIN_VERSION_ghc_typelits_extra(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  4 || \
  (major1) == 0 && (major2) == 4 && (minor) <= 8)
#endif /* MIN_VERSION_ghc_typelits_extra */
/* package ghc-typelits-knownnat-0.7.13 */
#ifndef VERSION_ghc_typelits_knownnat
#define VERSION_ghc_typelits_knownnat "0.7.13"
#endif /* VERSION_ghc_typelits_knownnat */
#ifndef MIN_VERSION_ghc_typelits_knownnat
#define MIN_VERSION_ghc_typelits_knownnat(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  7 || \
  (major1) == 0 && (major2) == 7 && (minor) <= 13)
#endif /* MIN_VERSION_ghc_typelits_knownnat */
/* package ghc-typelits-natnormalise-0.7.10 */
#ifndef VERSION_ghc_typelits_natnormalise
#define VERSION_ghc_typelits_natnormalise "0.7.10"
#endif /* VERSION_ghc_typelits_natnormalise */
#ifndef MIN_VERSION_ghc_typelits_natnormalise
#define MIN_VERSION_ghc_typelits_natnormalise(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  7 || \
  (major1) == 0 && (major2) == 7 && (minor) <= 10)
#endif /* MIN_VERSION_ghc_typelits_natnormalise */
/* package text-2.1.1 */
#ifndef VERSION_text
#define VERSION_text "2.1.1"
#endif /* VERSION_text */
#ifndef MIN_VERSION_text
#define MIN_VERSION_text(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  1 || \
  (major1) == 2 && (major2) == 1 && (minor) <= 1)
#endif /* MIN_VERSION_text */

/* tool gcc-15.2.1 */
#ifndef TOOL_VERSION_gcc
#define TOOL_VERSION_gcc "15.2.1"
#endif /* TOOL_VERSION_gcc */
#ifndef MIN_TOOL_VERSION_gcc
#define MIN_TOOL_VERSION_gcc(major1,major2,minor) (\
  (major1) <  15 || \
  (major1) == 15 && (major2) <  2 || \
  (major1) == 15 && (major2) == 2 && (minor) <= 1)
#endif /* MIN_TOOL_VERSION_gcc */
/* tool ghc-9.8.4 */
#ifndef TOOL_VERSION_ghc
#define TOOL_VERSION_ghc "9.8.4"
#endif /* TOOL_VERSION_ghc */
#ifndef MIN_TOOL_VERSION_ghc
#define MIN_TOOL_VERSION_ghc(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  8 || \
  (major1) == 9 && (major2) == 8 && (minor) <= 4)
#endif /* MIN_TOOL_VERSION_ghc */
/* tool ghc-pkg-9.8.4 */
#ifndef TOOL_VERSION_ghc_pkg
#define TOOL_VERSION_ghc_pkg "9.8.4"
#endif /* TOOL_VERSION_ghc_pkg */
#ifndef MIN_TOOL_VERSION_ghc_pkg
#define MIN_TOOL_VERSION_ghc_pkg(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  8 || \
  (major1) == 9 && (major2) == 8 && (minor) <= 4)
#endif /* MIN_TOOL_VERSION_ghc_pkg */
/* tool haddock-2.30.0 */
#ifndef TOOL_VERSION_haddock
#define TOOL_VERSION_haddock "2.30.0"
#endif /* TOOL_VERSION_haddock */
#ifndef MIN_TOOL_VERSION_haddock
#define MIN_TOOL_VERSION_haddock(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  30 || \
  (major1) == 2 && (major2) == 30 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_haddock */
/* tool happy-2.0.2 */
#ifndef TOOL_VERSION_happy
#define TOOL_VERSION_happy "2.0.2"
#endif /* TOOL_VERSION_happy */
#ifndef MIN_TOOL_VERSION_happy
#define MIN_TOOL_VERSION_happy(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  0 || \
  (major1) == 2 && (major2) == 0 && (minor) <= 2)
#endif /* MIN_TOOL_VERSION_happy */
/* tool hpc-0.69 */
#ifndef TOOL_VERSION_hpc
#define TOOL_VERSION_hpc "0.69"
#endif /* TOOL_VERSION_hpc */
#ifndef MIN_TOOL_VERSION_hpc
#define MIN_TOOL_VERSION_hpc(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  69 || \
  (major1) == 0 && (major2) == 69 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_hpc */
/* tool hsc2hs-0.68.10 */
#ifndef TOOL_VERSION_hsc2hs
#define TOOL_VERSION_hsc2hs "0.68.10"
#endif /* TOOL_VERSION_hsc2hs */
#ifndef MIN_TOOL_VERSION_hsc2hs
#define MIN_TOOL_VERSION_hsc2hs(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 10)
#endif /* MIN_TOOL_VERSION_hsc2hs */
/* tool pkg-config-2.5.1 */
#ifndef TOOL_VERSION_pkg_config
#define TOOL_VERSION_pkg_config "2.5.1"
#endif /* TOOL_VERSION_pkg_config */
#ifndef MIN_TOOL_VERSION_pkg_config
#define MIN_TOOL_VERSION_pkg_config(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  5 || \
  (major1) == 2 && (major2) == 5 && (minor) <= 1)
#endif /* MIN_TOOL_VERSION_pkg_config */
/* tool runghc-9.8.4 */
#ifndef TOOL_VERSION_runghc
#define TOOL_VERSION_runghc "9.8.4"
#endif /* TOOL_VERSION_runghc */
#ifndef MIN_TOOL_VERSION_runghc
#define MIN_TOOL_VERSION_runghc(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  8 || \
  (major1) == 9 && (major2) == 8 && (minor) <= 4)
#endif /* MIN_TOOL_VERSION_runghc */
/* tool strip-2.45 */
#ifndef TOOL_VERSION_strip
#define TOOL_VERSION_strip "2.45"
#endif /* TOOL_VERSION_strip */
#ifndef MIN_TOOL_VERSION_strip
#define MIN_TOOL_VERSION_strip(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  45 || \
  (major1) == 2 && (major2) == 45 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_strip */

#ifndef CURRENT_PACKAGE_KEY
#define CURRENT_PACKAGE_KEY "clash-assignments-0.1-Lm3EieMLNNb9m3AoDw4eF0"
#endif /* CURRENT_packageKey */
#ifndef CURRENT_COMPONENT_ID
#define CURRENT_COMPONENT_ID "clash-assignments-0.1-Lm3EieMLNNb9m3AoDw4eF0"
#endif /* CURRENT_COMPONENT_ID */
#ifndef CURRENT_PACKAGE_VERSION
#define CURRENT_PACKAGE_VERSION "0.1"
#endif /* CURRENT_PACKAGE_VERSION */

#undef CURRENT_PACKAGE_KEY
#undef CURRENT_COMPONENT_ID
/* DO NOT EDIT: This file is automatically generated by Cabal */

/* package clash-assignments-0.1 */
#ifndef VERSION_clash_assignments
#define VERSION_clash_assignments "0.1"
#endif /* VERSION_clash_assignments */
#ifndef MIN_VERSION_clash_assignments
#define MIN_VERSION_clash_assignments(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 0)
#endif /* MIN_VERSION_clash_assignments */
/* package base-4.19.2.0 */
#ifndef VERSION_base
#define VERSION_base "4.19.2.0"
#endif /* VERSION_base */
#ifndef MIN_VERSION_base
#define MIN_VERSION_base(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  19 || \
  (major1) == 4 && (major2) == 19 && (minor) <= 2)
#endif /* MIN_VERSION_base */
/* package clash-assignments-0.1 */
#ifndef VERSION_clash_assignments
#define VERSION_clash_assignments "0.1"
#endif /* VERSION_clash_assignments */
#ifndef MIN_VERSION_clash_assignments
#define MIN_VERSION_clash_assignments(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 0)
#endif /* MIN_VERSION_clash_assignments */
/* package clash-ghc-1.8.4 */
#ifndef VERSION_clash_ghc
#define VERSION_clash_ghc "1.8.4"
#endif /* VERSION_clash_ghc */
#ifndef MIN_VERSION_clash_ghc
#define MIN_VERSION_clash_ghc(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  8 || \
  (major1) == 1 && (major2) == 8 && (minor) <= 4)
#endif /* MIN_VERSION_clash_ghc */

/* tool gcc-15.2.1 */
#ifndef TOOL_VERSION_gcc
#define TOOL_VERSION_gcc "15.2.1"
#endif /* TOOL_VERSION_gcc */
#ifndef MIN_TOOL_VERSION_gcc
#define MIN_TOOL_VERSION_gcc(major1,major2,minor) (\
  (major1) <  15 || \
  (major1) == 15 && (major2) <  2 || \
  (major1) == 15 && (major2) == 2 && (minor) <= 1)
#endif /* MIN_TOOL_VERSION_gcc */
/* tool ghc-9.8.4 */
#ifndef TOOL_VERSION_ghc
#define TOOL_VERSION_ghc "9.8.4"
#endif /* TOOL_VERSION_ghc */
#ifndef MIN_TOOL_VERSION_ghc
#define MIN_TOOL_VERSION_ghc(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  8 || \
  (major1) == 9 && (major2) == 8 && (minor) <= 4)
#endif /* MIN_TOOL_VERSION_ghc */
/* tool ghc-pkg-9.8.4 */
#ifndef TOOL_VERSION_ghc_pkg
#define TOOL_VERSION_ghc_pkg "9.8.4"
#endif /* TOOL_VERSION_ghc_pkg */
#ifndef MIN_TOOL_VERSION_ghc_pkg
#define MIN_TOOL_VERSION_ghc_pkg(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  8 || \
  (major1) == 9 && (major2) == 8 && (minor) <= 4)
#endif /* MIN_TOOL_VERSION_ghc_pkg */
/* tool haddock-2.30.0 */
#ifndef TOOL_VERSION_haddock
#define TOOL_VERSION_haddock "2.30.0"
#endif /* TOOL_VERSION_haddock */
#ifndef MIN_TOOL_VERSION_haddock
#define MIN_TOOL_VERSION_haddock(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  30 || \
  (major1) == 2 && (major2) == 30 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_haddock */
/* tool happy-2.0.2 */
#ifndef TOOL_VERSION_happy
#define TOOL_VERSION_happy "2.0.2"
#endif /* TOOL_VERSION_happy */
#ifndef MIN_TOOL_VERSION_happy
#define MIN_TOOL_VERSION_happy(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  0 || \
  (major1) == 2 && (major2) == 0 && (minor) <= 2)
#endif /* MIN_TOOL_VERSION_happy */
/* tool hpc-0.69 */
#ifndef TOOL_VERSION_hpc
#define TOOL_VERSION_hpc "0.69"
#endif /* TOOL_VERSION_hpc */
#ifndef MIN_TOOL_VERSION_hpc
#define MIN_TOOL_VERSION_hpc(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  69 || \
  (major1) == 0 && (major2) == 69 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_hpc */
/* tool hsc2hs-0.68.10 */
#ifndef TOOL_VERSION_hsc2hs
#define TOOL_VERSION_hsc2hs "0.68.10"
#endif /* TOOL_VERSION_hsc2hs */
#ifndef MIN_TOOL_VERSION_hsc2hs
#define MIN_TOOL_VERSION_hsc2hs(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 10)
#endif /* MIN_TOOL_VERSION_hsc2hs */
/* tool pkg-config-2.5.1 */
#ifndef TOOL_VERSION_pkg_config
#define TOOL_VERSION_pkg_config "2.5.1"
#endif /* TOOL_VERSION_pkg_config */
#ifndef MIN_TOOL_VERSION_pkg_config
#define MIN_TOOL_VERSION_pkg_config(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  5 || \
  (major1) == 2 && (major2) == 5 && (minor) <= 1)
#endif /* MIN_TOOL_VERSION_pkg_config */
/* tool runghc-9.8.4 */
#ifndef TOOL_VERSION_runghc
#define TOOL_VERSION_runghc "9.8.4"
#endif /* TOOL_VERSION_runghc */
#ifndef MIN_TOOL_VERSION_runghc
#define MIN_TOOL_VERSION_runghc(major1,major2,minor) (\
  (major1) <  9 || \
  (major1) == 9 && (major2) <  8 || \
  (major1) == 9 && (major2) == 8 && (minor) <= 4)
#endif /* MIN_TOOL_VERSION_runghc */
/* tool strip-2.45 */
#ifndef TOOL_VERSION_strip
#define TOOL_VERSION_strip "2.45"
#endif /* TOOL_VERSION_strip */
#ifndef MIN_TOOL_VERSION_strip
#define MIN_TOOL_VERSION_strip(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  45 || \
  (major1) == 2 && (major2) == 45 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_strip */

#ifndef CURRENT_COMPONENT_ID
#define CURRENT_COMPONENT_ID "clash-assignments-0.1-xwmB03CtxCKq4ahbrco61-clash"
#endif /* CURRENT_COMPONENT_ID */
#ifndef CURRENT_PACKAGE_VERSION
#define CURRENT_PACKAGE_VERSION "0.1"
#endif /* CURRENT_PACKAGE_VERSION */

#undef CURRENT_PACKAGE_KEY
#undef CURRENT_COMPONENT_ID
