[env:sense_example_bmi270]
platform = nordicnrf52
board = nano33ble
framework = arduino
monitor_speed = 115200

; Force PlatformIO to use a newer GCC toolchain that supports C++20
; platform_packages =
;     toolchain-gccarmnoneeabi@~1.100301.0

lib_extra_dirs =
    ../../lib
    ../../external
    ../../external/fusion

lib_ignore =
	eigen ; Otherwise it tries to compile files in their test/ and bench/

build_unflags =
    -std=gnu++11
    -std=gnu++14
    -std=gnu++17
    -std=c++11
    -std=c++14
    ; -std=c++17

build_flags =
    -std=gnu++17
    ; -std=gnu++20
    -Wall
	-Wextra
	-Werror
	; -Wno-volatile
	; For MPU6050.
	; -DTINY_MPU6050_WHOAMI_VALUE=0x68
    ; For MPU6500.
    -DTINY_MPU6050_WHOAMI_VALUE=0x70
	-DTARGET_PLATFORM=ARDUINO
	-DTARGET_PLATFORM_ARDUINO
	-DFUSION_USE_NORMAL_SQRT

	; https://github.com/arduino/ArduinoCore-mbed/issues/1024
	-DMBED_CONF_NORDIC_NRF_LF_CLOCK_SRC=NRF_LF_SRC_XTAL

	; Explicitly tell the compiler where to find the deeply nested headers
    -I../../external/fusion/madgwick/include
    -I../../external/fusion/madgwick/
    -I../../external/tl/include
    -I../../external/fmt/include
    -I../../external/eigen/

extra_scripts = pre:./platformio/ignore_examples.py
