[env:disco_l475vg_iot01a]
platform = ststm32
board = disco_l475vg_iot01a
framework = arduino

# Monitor speed matches Serial.begin(115200)
monitor_speed = 9600

# Connection settings
upload_protocol = stlink

# Dependency (Correct One)
lib_deps =
    stm32duino/STM32duino ISM43362-M3G-L44 @ ^1.1.1
    SPI

# BUILD FLAGS: REMOVED -DUSBCON
# This forces Serial to use the ST-Link (UART) connection
build_flags = 
    -DHAL_UART_MODULE_ENABLED
